//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.24 at 05:32:16 PM CEST 
//
package be.fedict.eidtoolset.eidlibrary;

import javax.xml.bind.DatatypeConverter;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dirFile">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="2F00" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BelPicDirectory">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="objectDirectoryFile">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5031" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="tokenInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5032" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="authenticationObjectDirectoryFile">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5034" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="privateKeyDirectoryFile">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5035" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="certificateDirectoryFile">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5037" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="authenticationCertificate">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5038" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="nonRepudiationCertificate">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5039" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="caCertificate">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="503A" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="rootCaCertificate">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="503B" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="rrnCertificate">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="503C" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="DF00" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IDDirectory">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="identityFile">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4031" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="identityFileSignature">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4032" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="addressFile">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4033" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="addressFileSignature">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4034" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="photoFile">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4035" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="caRoleIDFile">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4038" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="preferencesFile">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4039" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="DF01" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="3F00" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "dirFile", "belPicDirectory", "idDirectory" })
@XmlRootElement(name = "MasterFile")
public class MasterFile {
	@XmlElement(required = true)
	protected MasterFile.DirFile dirFile;
	@XmlElement(name = "BelPicDirectory", required = true)
	protected MasterFile.BelPicDirectory belPicDirectory;
	@XmlElement(name = "IDDirectory", required = true)
	protected MasterFile.IDDirectory idDirectory;
	@XmlAttribute
	protected byte[] fileID;
	/**
	 * Gets the value of the dirFile property.
	 * 
	 * @return possible object is {@link MasterFile.DirFile }
	 * 
	 */
	public MasterFile.DirFile getDirFile() {
		return dirFile;
	}
	/**
	 * Sets the value of the dirFile property.
	 * 
	 * @param value
	 *            allowed object is {@link MasterFile.DirFile }
	 * 
	 */
	public void setDirFile(MasterFile.DirFile value) {
		this.dirFile = value;
	}
	/**
	 * Gets the value of the belPicDirectory property.
	 * 
	 * @return possible object is {@link MasterFile.BelPicDirectory }
	 * 
	 */
	public MasterFile.BelPicDirectory getBelPicDirectory() {
		return belPicDirectory;
	}
	/**
	 * Sets the value of the belPicDirectory property.
	 * 
	 * @param value
	 *            allowed object is {@link MasterFile.BelPicDirectory }
	 * 
	 */
	public void setBelPicDirectory(MasterFile.BelPicDirectory value) {
		this.belPicDirectory = value;
	}
	/**
	 * Gets the value of the idDirectory property.
	 * 
	 * @return possible object is {@link MasterFile.IDDirectory }
	 * 
	 */
	public MasterFile.IDDirectory getIDDirectory() {
		return idDirectory;
	}
	/**
	 * Sets the value of the idDirectory property.
	 * 
	 * @param value
	 *            allowed object is {@link MasterFile.IDDirectory }
	 * 
	 */
	public void setIDDirectory(MasterFile.IDDirectory value) {
		this.idDirectory = value;
	}
	/**
	 * Gets the value of the fileID property.
	 * 
	 * @return possible object is byte[]
	 */
	public byte[] getFileID() {
		if (fileID == null) {
			return DatatypeConverter.parseBase64Binary("3F00");
		} else {
			return fileID;
		}
	}
	/**
	 * Sets the value of the fileID property.
	 * 
	 * @param value
	 *            allowed object is byte[]
	 */
	public void setFileID(byte[] value) {
		this.fileID = ((byte[]) value);
	}
	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="objectDirectoryFile">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5031" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="tokenInfo">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5032" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="authenticationObjectDirectoryFile">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5034" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="privateKeyDirectoryFile">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5035" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="certificateDirectoryFile">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5037" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="authenticationCertificate">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5038" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="nonRepudiationCertificate">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5039" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="caCertificate">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="503A" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="rootCaCertificate">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="503B" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="rrnCertificate">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="503C" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="DF00" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "objectDirectoryFile", "tokenInfo", "authenticationObjectDirectoryFile", "privateKeyDirectoryFile", "certificateDirectoryFile", "authenticationCertificate", "nonRepudiationCertificate", "caCertificate",
			"rootCaCertificate", "rrnCertificate" })
	public static class BelPicDirectory {
		@XmlElement(required = true)
		protected MasterFile.BelPicDirectory.ObjectDirectoryFile objectDirectoryFile;
		@XmlElement(required = true)
		protected MasterFile.BelPicDirectory.TokenInfo tokenInfo;
		@XmlElement(required = true)
		protected MasterFile.BelPicDirectory.AuthenticationObjectDirectoryFile authenticationObjectDirectoryFile;
		@XmlElement(required = true)
		protected MasterFile.BelPicDirectory.PrivateKeyDirectoryFile privateKeyDirectoryFile;
		@XmlElement(required = true)
		protected MasterFile.BelPicDirectory.CertificateDirectoryFile certificateDirectoryFile;
		@XmlElement(required = true)
		protected MasterFile.BelPicDirectory.AuthenticationCertificate authenticationCertificate;
		@XmlElement(required = true)
		protected MasterFile.BelPicDirectory.NonRepudiationCertificate nonRepudiationCertificate;
		@XmlElement(required = true)
		protected MasterFile.BelPicDirectory.CaCertificate caCertificate;
		@XmlElement(required = true)
		protected MasterFile.BelPicDirectory.RootCaCertificate rootCaCertificate;
		@XmlElement(required = true)
		protected MasterFile.BelPicDirectory.RrnCertificate rrnCertificate;
		@XmlAttribute
		protected byte[] fileID;
		/**
		 * Gets the value of the objectDirectoryFile property.
		 * 
		 * @return possible object is
		 *         {@link MasterFile.BelPicDirectory.ObjectDirectoryFile }
		 * 
		 */
		public MasterFile.BelPicDirectory.ObjectDirectoryFile getObjectDirectoryFile() {
			return objectDirectoryFile;
		}
		/**
		 * Sets the value of the objectDirectoryFile property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link MasterFile.BelPicDirectory.ObjectDirectoryFile }
		 * 
		 */
		public void setObjectDirectoryFile(MasterFile.BelPicDirectory.ObjectDirectoryFile value) {
			this.objectDirectoryFile = value;
		}
		/**
		 * Gets the value of the tokenInfo property.
		 * 
		 * @return possible object is
		 *         {@link MasterFile.BelPicDirectory.TokenInfo }
		 * 
		 */
		public MasterFile.BelPicDirectory.TokenInfo getTokenInfo() {
			return tokenInfo;
		}
		/**
		 * Sets the value of the tokenInfo property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link MasterFile.BelPicDirectory.TokenInfo }
		 * 
		 */
		public void setTokenInfo(MasterFile.BelPicDirectory.TokenInfo value) {
			this.tokenInfo = value;
		}
		/**
		 * Gets the value of the authenticationObjectDirectoryFile property.
		 * 
		 * @return possible object is
		 *         {@link MasterFile.BelPicDirectory.AuthenticationObjectDirectoryFile }
		 * 
		 */
		public MasterFile.BelPicDirectory.AuthenticationObjectDirectoryFile getAuthenticationObjectDirectoryFile() {
			return authenticationObjectDirectoryFile;
		}
		/**
		 * Sets the value of the authenticationObjectDirectoryFile property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link MasterFile.BelPicDirectory.AuthenticationObjectDirectoryFile }
		 * 
		 */
		public void setAuthenticationObjectDirectoryFile(MasterFile.BelPicDirectory.AuthenticationObjectDirectoryFile value) {
			this.authenticationObjectDirectoryFile = value;
		}
		/**
		 * Gets the value of the privateKeyDirectoryFile property.
		 * 
		 * @return possible object is
		 *         {@link MasterFile.BelPicDirectory.PrivateKeyDirectoryFile }
		 * 
		 */
		public MasterFile.BelPicDirectory.PrivateKeyDirectoryFile getPrivateKeyDirectoryFile() {
			return privateKeyDirectoryFile;
		}
		/**
		 * Sets the value of the privateKeyDirectoryFile property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link MasterFile.BelPicDirectory.PrivateKeyDirectoryFile }
		 * 
		 */
		public void setPrivateKeyDirectoryFile(MasterFile.BelPicDirectory.PrivateKeyDirectoryFile value) {
			this.privateKeyDirectoryFile = value;
		}
		/**
		 * Gets the value of the certificateDirectoryFile property.
		 * 
		 * @return possible object is
		 *         {@link MasterFile.BelPicDirectory.CertificateDirectoryFile }
		 * 
		 */
		public MasterFile.BelPicDirectory.CertificateDirectoryFile getCertificateDirectoryFile() {
			return certificateDirectoryFile;
		}
		/**
		 * Sets the value of the certificateDirectoryFile property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link MasterFile.BelPicDirectory.CertificateDirectoryFile }
		 * 
		 */
		public void setCertificateDirectoryFile(MasterFile.BelPicDirectory.CertificateDirectoryFile value) {
			this.certificateDirectoryFile = value;
		}
		/**
		 * Gets the value of the authenticationCertificate property.
		 * 
		 * @return possible object is
		 *         {@link MasterFile.BelPicDirectory.AuthenticationCertificate }
		 * 
		 */
		public MasterFile.BelPicDirectory.AuthenticationCertificate getAuthenticationCertificate() {
			return authenticationCertificate;
		}
		/**
		 * Sets the value of the authenticationCertificate property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link MasterFile.BelPicDirectory.AuthenticationCertificate }
		 * 
		 */
		public void setAuthenticationCertificate(MasterFile.BelPicDirectory.AuthenticationCertificate value) {
			this.authenticationCertificate = value;
		}
		/**
		 * Gets the value of the nonRepudiationCertificate property.
		 * 
		 * @return possible object is
		 *         {@link MasterFile.BelPicDirectory.NonRepudiationCertificate }
		 * 
		 */
		public MasterFile.BelPicDirectory.NonRepudiationCertificate getNonRepudiationCertificate() {
			return nonRepudiationCertificate;
		}
		/**
		 * Sets the value of the nonRepudiationCertificate property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link MasterFile.BelPicDirectory.NonRepudiationCertificate }
		 * 
		 */
		public void setNonRepudiationCertificate(MasterFile.BelPicDirectory.NonRepudiationCertificate value) {
			this.nonRepudiationCertificate = value;
		}
		/**
		 * Gets the value of the caCertificate property.
		 * 
		 * @return possible object is
		 *         {@link MasterFile.BelPicDirectory.CaCertificate }
		 * 
		 */
		public MasterFile.BelPicDirectory.CaCertificate getCaCertificate() {
			return caCertificate;
		}
		/**
		 * Sets the value of the caCertificate property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link MasterFile.BelPicDirectory.CaCertificate }
		 * 
		 */
		public void setCaCertificate(MasterFile.BelPicDirectory.CaCertificate value) {
			this.caCertificate = value;
		}
		/**
		 * Gets the value of the rootCaCertificate property.
		 * 
		 * @return possible object is
		 *         {@link MasterFile.BelPicDirectory.RootCaCertificate }
		 * 
		 */
		public MasterFile.BelPicDirectory.RootCaCertificate getRootCaCertificate() {
			return rootCaCertificate;
		}
		/**
		 * Sets the value of the rootCaCertificate property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link MasterFile.BelPicDirectory.RootCaCertificate }
		 * 
		 */
		public void setRootCaCertificate(MasterFile.BelPicDirectory.RootCaCertificate value) {
			this.rootCaCertificate = value;
		}
		/**
		 * Gets the value of the rrnCertificate property.
		 * 
		 * @return possible object is
		 *         {@link MasterFile.BelPicDirectory.RrnCertificate }
		 * 
		 */
		public MasterFile.BelPicDirectory.RrnCertificate getRrnCertificate() {
			return rrnCertificate;
		}
		/**
		 * Sets the value of the rrnCertificate property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link MasterFile.BelPicDirectory.RrnCertificate }
		 * 
		 */
		public void setRrnCertificate(MasterFile.BelPicDirectory.RrnCertificate value) {
			this.rrnCertificate = value;
		}
		/**
		 * Gets the value of the fileID property.
		 * 
		 * @return possible object is byte[]
		 */
		public byte[] getFileID() {
			if (fileID == null) {
				return DatatypeConverter.parseBase64Binary("DF00");
			} else {
				return fileID;
			}
		}
		/**
		 * Sets the value of the fileID property.
		 * 
		 * @param value
		 *            allowed object is byte[]
		 */
		public void setFileID(byte[] value) {
			this.fileID = ((byte[]) value);
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5038" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class AuthenticationCertificate {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("5038");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5034" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class AuthenticationObjectDirectoryFile {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("5034");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="503A" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class CaCertificate {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("503A");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5037" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class CertificateDirectoryFile {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("5037");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5039" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class NonRepudiationCertificate {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("5039");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5031" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class ObjectDirectoryFile {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("5031");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5035" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class PrivateKeyDirectoryFile {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("5035");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="503B" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class RootCaCertificate {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("503B");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="503C" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class RrnCertificate {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("503C");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="5032" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class TokenInfo {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("5032");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
	}
	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *       &lt;/sequence>
	 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="2F00" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "fileData" })
	public static class DirFile {
		@XmlElement(required = true)
		protected byte[] fileData;
		@XmlAttribute
		protected byte[] fileID;
		/**
		 * Gets the value of the fileData property.
		 * 
		 * @return possible object is byte[]
		 */
		public byte[] getFileData() {
			return fileData;
		}
		/**
		 * Sets the value of the fileData property.
		 * 
		 * @param value
		 *            allowed object is byte[]
		 */
		public void setFileData(byte[] value) {
			this.fileData = ((byte[]) value);
		}
		/**
		 * Gets the value of the fileID property.
		 * 
		 * @return possible object is byte[]
		 */
		public byte[] getFileID() {
			if (fileID == null) {
				return DatatypeConverter.parseBase64Binary("2F00");
			} else {
				return fileID;
			}
		}
		/**
		 * Sets the value of the fileID property.
		 * 
		 * @param value
		 *            allowed object is byte[]
		 */
		public void setFileID(byte[] value) {
			this.fileID = ((byte[]) value);
		}
	}
	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="identityFile">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4031" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="identityFileSignature">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4032" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="addressFile">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4033" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="addressFileSignature">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4034" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="photoFile">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4035" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="caRoleIDFile">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4038" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="preferencesFile">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4039" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="DF01" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "identityFile", "identityFileSignature", "addressFile", "addressFileSignature", "photoFile", "caRoleIDFile", "preferencesFile" })
	public static class IDDirectory {
		@XmlElement(required = true)
		protected MasterFile.IDDirectory.IdentityFile identityFile;
		@XmlElement(required = true)
		protected MasterFile.IDDirectory.IdentityFileSignature identityFileSignature;
		@XmlElement(required = true)
		protected MasterFile.IDDirectory.AddressFile addressFile;
		@XmlElement(required = true)
		protected MasterFile.IDDirectory.AddressFileSignature addressFileSignature;
		@XmlElement(required = true)
		protected MasterFile.IDDirectory.PhotoFile photoFile;
		@XmlElement(required = true)
		protected MasterFile.IDDirectory.CaRoleIDFile caRoleIDFile;
		@XmlElement(required = true)
		protected MasterFile.IDDirectory.PreferencesFile preferencesFile;
		@XmlAttribute
		protected byte[] fileID;
		/**
		 * Gets the value of the identityFile property.
		 * 
		 * @return possible object is
		 *         {@link MasterFile.IDDirectory.IdentityFile }
		 * 
		 */
		public MasterFile.IDDirectory.IdentityFile getIdentityFile() {
			return identityFile;
		}
		/**
		 * Sets the value of the identityFile property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link MasterFile.IDDirectory.IdentityFile }
		 * 
		 */
		public void setIdentityFile(MasterFile.IDDirectory.IdentityFile value) {
			this.identityFile = value;
		}
		/**
		 * Gets the value of the identityFileSignature property.
		 * 
		 * @return possible object is
		 *         {@link MasterFile.IDDirectory.IdentityFileSignature }
		 * 
		 */
		public MasterFile.IDDirectory.IdentityFileSignature getIdentityFileSignature() {
			return identityFileSignature;
		}
		/**
		 * Sets the value of the identityFileSignature property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link MasterFile.IDDirectory.IdentityFileSignature }
		 * 
		 */
		public void setIdentityFileSignature(MasterFile.IDDirectory.IdentityFileSignature value) {
			this.identityFileSignature = value;
		}
		/**
		 * Gets the value of the addressFile property.
		 * 
		 * @return possible object is {@link MasterFile.IDDirectory.AddressFile }
		 * 
		 */
		public MasterFile.IDDirectory.AddressFile getAddressFile() {
			return addressFile;
		}
		/**
		 * Sets the value of the addressFile property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link MasterFile.IDDirectory.AddressFile }
		 * 
		 */
		public void setAddressFile(MasterFile.IDDirectory.AddressFile value) {
			this.addressFile = value;
		}
		/**
		 * Gets the value of the addressFileSignature property.
		 * 
		 * @return possible object is
		 *         {@link MasterFile.IDDirectory.AddressFileSignature }
		 * 
		 */
		public MasterFile.IDDirectory.AddressFileSignature getAddressFileSignature() {
			return addressFileSignature;
		}
		/**
		 * Sets the value of the addressFileSignature property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link MasterFile.IDDirectory.AddressFileSignature }
		 * 
		 */
		public void setAddressFileSignature(MasterFile.IDDirectory.AddressFileSignature value) {
			this.addressFileSignature = value;
		}
		/**
		 * Gets the value of the photoFile property.
		 * 
		 * @return possible object is {@link MasterFile.IDDirectory.PhotoFile }
		 * 
		 */
		public MasterFile.IDDirectory.PhotoFile getPhotoFile() {
			return photoFile;
		}
		/**
		 * Sets the value of the photoFile property.
		 * 
		 * @param value
		 *            allowed object is {@link MasterFile.IDDirectory.PhotoFile }
		 * 
		 */
		public void setPhotoFile(MasterFile.IDDirectory.PhotoFile value) {
			this.photoFile = value;
		}
		/**
		 * Gets the value of the caRoleIDFile property.
		 * 
		 * @return possible object is
		 *         {@link MasterFile.IDDirectory.CaRoleIDFile }
		 * 
		 */
		public MasterFile.IDDirectory.CaRoleIDFile getCaRoleIDFile() {
			return caRoleIDFile;
		}
		/**
		 * Sets the value of the caRoleIDFile property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link MasterFile.IDDirectory.CaRoleIDFile }
		 * 
		 */
		public void setCaRoleIDFile(MasterFile.IDDirectory.CaRoleIDFile value) {
			this.caRoleIDFile = value;
		}
		/**
		 * Gets the value of the preferencesFile property.
		 * 
		 * @return possible object is
		 *         {@link MasterFile.IDDirectory.PreferencesFile }
		 * 
		 */
		public MasterFile.IDDirectory.PreferencesFile getPreferencesFile() {
			return preferencesFile;
		}
		/**
		 * Sets the value of the preferencesFile property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link MasterFile.IDDirectory.PreferencesFile }
		 * 
		 */
		public void setPreferencesFile(MasterFile.IDDirectory.PreferencesFile value) {
			this.preferencesFile = value;
		}
		/**
		 * Gets the value of the fileID property.
		 * 
		 * @return possible object is byte[]
		 */
		public byte[] getFileID() {
			if (fileID == null) {
				return DatatypeConverter.parseBase64Binary("DF01");
			} else {
				return fileID;
			}
		}
		/**
		 * Sets the value of the fileID property.
		 * 
		 * @param value
		 *            allowed object is byte[]
		 */
		public void setFileID(byte[] value) {
			this.fileID = ((byte[]) value);
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4033" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class AddressFile {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("4033");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4034" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class AddressFileSignature {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("4034");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4038" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class CaRoleIDFile {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("4038");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4031" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class IdentityFile {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("4031");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4032" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class IdentityFileSignature {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("4032");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4035" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class PhotoFile {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("4035");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="fileData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="fileID" type="{http://www.w3.org/2001/XMLSchema}base64Binary" fixed="4039" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "fileData" })
		public static class PreferencesFile {
			@XmlElement(required = true)
			protected byte[] fileData;
			@XmlAttribute
			protected byte[] fileID;
			/**
			 * Gets the value of the fileData property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileData() {
				return fileData;
			}
			/**
			 * Sets the value of the fileData property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileData(byte[] value) {
				this.fileData = ((byte[]) value);
			}
			/**
			 * Gets the value of the fileID property.
			 * 
			 * @return possible object is byte[]
			 */
			public byte[] getFileID() {
				if (fileID == null) {
					return DatatypeConverter.parseBase64Binary("4039");
				} else {
					return fileID;
				}
			}
			/**
			 * Sets the value of the fileID property.
			 * 
			 * @param value
			 *            allowed object is byte[]
			 */
			public void setFileID(byte[] value) {
				this.fileID = ((byte[]) value);
			}
		}
	}
}
