//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.14 at 10:09:58 AM CEST 
//


package be.fedict.eidtoolset.eidlibrary;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.fedict.eidtoolset.eidlibrary package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.fedict.eidtoolset.eidlibrary
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MasterFile.IDDirectory }
     * 
     */
    public MasterFile.IDDirectory createMasterFileIDDirectory() {
        return new MasterFile.IDDirectory();
    }

    /**
     * Create an instance of {@link MasterFile.IDDirectory.AddressFile }
     * 
     */
    public MasterFile.IDDirectory.AddressFile createMasterFileIDDirectoryAddressFile() {
        return new MasterFile.IDDirectory.AddressFile();
    }

    /**
     * Create an instance of {@link MasterFile.BelPicDirectory.ObjectDirectoryFile }
     * 
     */
    public MasterFile.BelPicDirectory.ObjectDirectoryFile createMasterFileBelPicDirectoryObjectDirectoryFile() {
        return new MasterFile.BelPicDirectory.ObjectDirectoryFile();
    }

    /**
     * Create an instance of {@link MasterFile.BelPicDirectory.TokenInfo }
     * 
     */
    public MasterFile.BelPicDirectory.TokenInfo createMasterFileBelPicDirectoryTokenInfo() {
        return new MasterFile.BelPicDirectory.TokenInfo();
    }

    /**
     * Create an instance of {@link MasterFile.BelPicDirectory.RootCaCertificate }
     * 
     */
    public MasterFile.BelPicDirectory.RootCaCertificate createMasterFileBelPicDirectoryRootCaCertificate() {
        return new MasterFile.BelPicDirectory.RootCaCertificate();
    }

    /**
     * Create an instance of {@link MasterFile.BelPicDirectory.CaCertificate }
     * 
     */
    public MasterFile.BelPicDirectory.CaCertificate createMasterFileBelPicDirectoryCaCertificate() {
        return new MasterFile.BelPicDirectory.CaCertificate();
    }

    /**
     * Create an instance of {@link MasterFile.BelPicDirectory.PrivateKeyDirectoryFile }
     * 
     */
    public MasterFile.BelPicDirectory.PrivateKeyDirectoryFile createMasterFileBelPicDirectoryPrivateKeyDirectoryFile() {
        return new MasterFile.BelPicDirectory.PrivateKeyDirectoryFile();
    }

    /**
     * Create an instance of {@link MasterFile.IDDirectory.PhotoFile }
     * 
     */
    public MasterFile.IDDirectory.PhotoFile createMasterFileIDDirectoryPhotoFile() {
        return new MasterFile.IDDirectory.PhotoFile();
    }

    /**
     * Create an instance of {@link MasterFile.BelPicDirectory.AuthenticationCertificate }
     * 
     */
    public MasterFile.BelPicDirectory.AuthenticationCertificate createMasterFileBelPicDirectoryAuthenticationCertificate() {
        return new MasterFile.BelPicDirectory.AuthenticationCertificate();
    }

    /**
     * Create an instance of {@link MasterFile }
     * 
     */
    public MasterFile createMasterFile() {
        return new MasterFile();
    }

    /**
     * Create an instance of {@link MasterFile.IDDirectory.IdentityFileSignature }
     * 
     */
    public MasterFile.IDDirectory.IdentityFileSignature createMasterFileIDDirectoryIdentityFileSignature() {
        return new MasterFile.IDDirectory.IdentityFileSignature();
    }

    /**
     * Create an instance of {@link MasterFile.IDDirectory.AddressFileSignature }
     * 
     */
    public MasterFile.IDDirectory.AddressFileSignature createMasterFileIDDirectoryAddressFileSignature() {
        return new MasterFile.IDDirectory.AddressFileSignature();
    }

    /**
     * Create an instance of {@link MasterFile.BelPicDirectory.AuthenticationObjectDirectoryFile }
     * 
     */
    public MasterFile.BelPicDirectory.AuthenticationObjectDirectoryFile createMasterFileBelPicDirectoryAuthenticationObjectDirectoryFile() {
        return new MasterFile.BelPicDirectory.AuthenticationObjectDirectoryFile();
    }

    /**
     * Create an instance of {@link MasterFile.BelPicDirectory.RrnCertificate }
     * 
     */
    public MasterFile.BelPicDirectory.RrnCertificate createMasterFileBelPicDirectoryRrnCertificate() {
        return new MasterFile.BelPicDirectory.RrnCertificate();
    }

    /**
     * Create an instance of {@link MasterFile.IDDirectory.PreferencesFile }
     * 
     */
    public MasterFile.IDDirectory.PreferencesFile createMasterFileIDDirectoryPreferencesFile() {
        return new MasterFile.IDDirectory.PreferencesFile();
    }

    /**
     * Create an instance of {@link MasterFile.BelPicDirectory.CertificateDirectoryFile }
     * 
     */
    public MasterFile.BelPicDirectory.CertificateDirectoryFile createMasterFileBelPicDirectoryCertificateDirectoryFile() {
        return new MasterFile.BelPicDirectory.CertificateDirectoryFile();
    }

    /**
     * Create an instance of {@link MasterFile.BelPicDirectory }
     * 
     */
    public MasterFile.BelPicDirectory createMasterFileBelPicDirectory() {
        return new MasterFile.BelPicDirectory();
    }

    /**
     * Create an instance of {@link MasterFile.IDDirectory.CaRoleIDFile }
     * 
     */
    public MasterFile.IDDirectory.CaRoleIDFile createMasterFileIDDirectoryCaRoleIDFile() {
        return new MasterFile.IDDirectory.CaRoleIDFile();
    }

    /**
     * Create an instance of {@link MasterFile.DirFile }
     * 
     */
    public MasterFile.DirFile createMasterFileDirFile() {
        return new MasterFile.DirFile();
    }

    /**
     * Create an instance of {@link MasterFile.BelPicDirectory.NonRepudiationCertificate }
     * 
     */
    public MasterFile.BelPicDirectory.NonRepudiationCertificate createMasterFileBelPicDirectoryNonRepudiationCertificate() {
        return new MasterFile.BelPicDirectory.NonRepudiationCertificate();
    }

    /**
     * Create an instance of {@link MasterFile.IDDirectory.IdentityFile }
     * 
     */
    public MasterFile.IDDirectory.IdentityFile createMasterFileIDDirectoryIdentityFile() {
        return new MasterFile.IDDirectory.IdentityFile();
    }

}
